#!/bin/bash
yarn build
ssh -i C:\\Users\\Admin\\Documents\\id_rsa.ppk root@107.170.121.178 pm2 stop server
ssh -i C:\\Users\\Admin\\Documents\\id_rsa.ppk root@107.170.121.178 rm -rf /home/keenethics
rsync -a ../keenethics/ root@107.170.121.178:/home/keenethics
sleep 5s
ssh -i C:\\Users\\Admin\\Documents\\id_rsa.ppk root@107.170.121.178 "cd /home/keenethics ; pm2 restart server.sh"
