#!/bin/bash
npm run build
ssh root@107.170.121.178 pm2 stop server
ssh root@107.170.121.178 rm -rf /home/keenethics
rsync -a --progress --exclude "node_modules" ../keenethics/ root@107.170.121.178:/home/keenethics
ssh root@107.170.121.178 "cd /home ; npm i"
ssh root@107.170.121.178 "cd /home/keenethics ; npm i"
ssh root@107.170.121.178 "cd /home/keenethics ; ENV_PATH=/home/.env npm run build"
ssh root@107.170.121.178 "cd /home/keenethics ; pm2 restart server.sh"
