#!/bin/bash
ssh root@167.71.71.176 pm2 stop server
ssh root@167.71.71.176 rm -rf /home/keenethics
rsync -a -h --exclude "node_modules" ../keenethics/ root@167.71.71.176:/home/keenethics
ssh root@167.71.71.176 "cd /home/keenethics ; npm i"
ssh root@167.71.71.176 "cd /home/keenethics ; npm run build"
ssh root@167.71.71.176 "cd /home/keenethics ; pm2 restart server.sh"
